WIP add sandbox_url option
own3d/own3dpro-obs-plugin pull request #23
Opened 2021-05-12 16:44 UTC by derpierre65

2021-05-13 19:23 UTC, ghostzero commented
Please provide a documentation example (how to use it).

2021-05-13 19:27 UTC, ghostzero requested changes
Please provide a documentation example. So we can maintain the [developer documentation](https://github.com/own3d/own3dpro-obs-plugin/wiki/Developer-Mode). This PR also has no description.

2021-05-14 07:03 UTC, ghostzero approved these changes
Looks now good to me

2021-05-14 07:45 UTC, Xaymar requested changes

2021-05-14 07:45 UTC, Xaymar commented on source/plugin.cpp
> +	std::string_view           URL_ENDPOINT_SANDBOX = get_sandbox_url();
std::string_view requires constant memory. std::string is deallocated before it is used, and will cause unexpected behavior.

2021-07-26 08:58 UTC, merged